# This is a basic workflow to help you get started with Actions

name: Generate Datas

on: 
schedule: # execute every 12 hours
  # Triggers the workflow on push or pull request events but only for the main branch
  -cron: " * */12 * * *"
  workflow_dispatch:
  
  jobs:
  build:
  name: Jobs to update datas
  runs-on: ubuntu-latest
  steps:
  # Snake Animation
  
  -uses: Platane/snk@master
  id: snake-gif
  width:
  github_user_name: SraSidle
  svg_out_path: dist/github-contribuition-grid-snake.svg
  
  - uses: crazy-max/ghaction-guthub-pages
  
  width:
  target_branch: output
  build_dir: dist
  env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

 
